#!/usr/bin/python

import feedparser
import sys
import datetime
import PyRSS2Gen
import os.path
import re

if len(sys.argv) < 3:
    print("Usage: " + sys.argv[0] + " <RSS URL> <output file>")
    sys.exit()

feed = sys.argv[1]
output = sys.argv[2]

comments = []
seen = {}

def rssEntry(entry):
    return PyRSS2Gen.RSSItem(
        title = re.sub(r'Comment on ', '', entry.title),
        link = entry.link,
        description = entry.description,
        guid = entry.guid,
        pubDate = entry.published)

# First read the cached comments from previous runs.
count = 0
if os.path.isfile(output):
    for entry in feedparser.parse(output).entries:
        count = count + 1
        if count < 15:
            seen[entry.link] = True
            comments.append(rssEntry(entry))

# Then add any new entries from Wordpress.
f = feedparser.parse(feed)
for entry in f.entries:
    if entry.author.find("Random Thoughts") == -1 and not seen.has_key(entry.link):
        comments.insert(0, rssEntry(entry))

rss = PyRSS2Gen.RSS2(
    title = f.feed.title,
    link = f.feed.link,
    description = f.feed.description,
    lastBuildDate = datetime.datetime.now(),
    items = comments)

rss.write_xml(open(output, "w"))
